[app]
name = "aitne_starter"
mode = "development"
entry_html = "index.html"

[build]
target = "js"
src_dir = "src"
out_dir = "."
style_root = ["./dist", "./public", "./src"]

[server]
host = "127.0.0.1"
port = 8000
